#!/bin/bash
# vim: set ft=sh

set -eu
set -o pipefail

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source $(dirname $0)/cf-functions.sh

working_dir=$1

if [ -z "$working_dir" ]; then
  echo "usage: $0 <path/to/source>"
  exit 1
fi

# for jq
PATH=/usr/local/bin:$PATH

TMPDIR=${TMPDIR:-/tmp}
payload=$(mktemp $TMPDIR/cf-cli-resource-request.XXXXXX)

cat > $payload <&0

debug=$(jq -r '.source.debug //empty' < $payload)
if [ "$debug" = "true" ]; then
  set -x
fi

api=$(jq -r '.source.api //empty' < $payload)
skip_cert_check=$(jq -r '.source.skip_cert_check //empty' < $payload)
username=$(jq -r '.source.username //empty' < $payload)
password=$(jq -r '.source.password //empty' < $payload)
source_org=$(jq -r '.source.org //empty' < $payload)
source_space=$(jq -r '.source.space //empty' < $payload)
params=$(jq -r '.params //empty' < $payload)

if [ -z "$api" ]; then
  echo "invalid payload (missing api)"
  exit 1
fi

if [ -z "$username" ]; then
  echo "invalid payload (missing username)"
  exit 1
fi

if [ -z "$password" ]; then
  echo "invalid payload (missing password)"
  exit 1
fi

cd $working_dir

cf_login $api "$username" "$password" $skip_cert_check

old_syntax=false
if echo $params | jq -e 'has("commands")' >/dev/null; then
  commands=$(echo $params | jq -r '.commands[].command')
elif echo $params | jq -e 'has("command")' >/dev/null; then
  # make the single command now plural
  params=$(jq -n --argjson params "$params" '{commands: [ $params ] }')
  commands=$(echo $params | jq -r '.commands[].command')
else
  commands=$(echo $params | jq -r 'keys_unsorted[]')
  old_syntax=true
fi

for command in $commands; do

  if $old_syntax ; then
    options=$(echo $params | jq --arg command $command '.[$command]')
    # convert underscores to hyphens in command names
    command=${command//_/-}
  else
    options=$(echo $params | jq --arg command $command '.commands[] | select(.command == $command)')
  fi

  org=$(echo $options | jq -r '.org //empty')
  [ -z "$org" ] && org=$source_org

  space=$(echo $options | jq -r '.space //empty')
  [ -z "$space" ] && space=$source_space

  if [ "create-org" = "$command" ]; then
    echo -e 'Executing \e[33m'"$command"$'\e[0m: '"$org"
    cf_create_org "$org"
  elif [ "delete-org" = "$command" ]; then
    echo -e 'Executing \e[33m'"$command"$'\e[0m: '"$org"
    cf_delete_org "$org"
  elif [ "create-space" = "$command" ]; then
    echo -e 'Executing \e[33m'"$command"$'\e[0m: '"$space"
    cf_create_space "$org" "$space"
  elif [ "delete-space" = "$command" ]; then
    echo -e 'Executing \e[33m'"$command"$'\e[0m: '"$space"
    cf_delete_space "$org" "$space"
  elif [ "create-service" = "$command" ]; then
    service=$(echo $options | jq -r '.service //empty')
    plan=$(echo $options | jq -r '.plan //empty')
    service_instance=$(echo $options | jq -r '.service_instance //empty')
    configuration=$(echo $options | jq -r '.configuration //"{}"')
    tags=$(echo $options | jq -r '.tags //empty')
    timeout=$(echo $options | jq -r '.timeout //empty')
    wait=$(echo $options | jq -r '.wait_for_service //"false"')
    echo -e 'Executing \e[33m'"$command"$'\e[0m: '"$service_instance"
    cf_target "$org" "$space"
    cf_create_service "$service" "$plan" "$service_instance" "$configuration" "$tags"
    if [ "true" = "$wait" ]; then
      cf_wait_for_service_instance "$service_instance" "$timeout"
    fi
  elif [ "wait-for-service" = "$command" ]; then
    service_instance=$(echo $options | jq -r '.service_instance //empty')
    timeout=$(echo $options | jq -r '.timeout //empty')
    echo -e 'Executing \e[33m'"$command"$'\e[0m: '"$service_instance"
    cf_target "$org" "$space"
    cf_wait_for_service_instance "$service_instance" "$timeout"
  elif [ "delete-service" = "$command" ]; then
    service_instance=$(echo $options | jq -r '.service_instance //empty')
    echo -e 'Executing \e[33m'"$command"$'\e[0m: '"$service_instance"
    cf_target "$org" "$space"
    cf_delete_service "$service_instance"
  elif [ "push" = "$command" ]; then
    app_name=$(echo $options | jq -r '.app_name //empty')
    hostname=$(echo $options | jq -r '.hostname //empty')
    memory=$(echo $options | jq -r '.memory //empty')
    disk_quota=$(echo $options | jq -r '.disk_quota //empty')
    instances=$(echo $options | jq -r '.instances //empty')
    path=$(echo $options | jq -r '.path //empty')
    buildpack=$(echo $options | jq -r '.buildpack //empty')
    no_start=$(echo $options | jq -r '.no_start //empty')
    manifest=$(echo $options | jq -r '.manifest //empty')

    args=
    [ -n "$app_name" ]   && args="$args $app_name"
    [ -n "$hostname" ]   && args="$args -n $hostname"
    [ -n "$memory" ]     && args="$args -m $memory"
    [ -n "$disk_quota" ] && args="$args -k $disk_quota"
    [ -n "$instances" ]  && args="$args -i $instances"
    [ -n "$path" ]       && args="$args -p $path"
    [ -n "$buildpack" ]  && args="$args -b $buildpack"
    [ -n "$manifest" ]   && args="$args -f $manifest"
    [ -n "$no_start" ]   && args="$args --no-start"

    echo -e 'Executing \e[33m'"$command"$'\e[0m: '"$app_name"
    cf_target "$org" "$space"
    cf_push "$args"
  elif [ "zero-downtime-push" = "$command" ]; then
    manifest=$(echo $options | jq -r '.manifest //empty')
    path=$(echo $options | jq -r '.path //empty')
    current_app_name=$(echo $options | jq -r '.current_app_name //empty')
    environment_variables=$(echo $options | jq -r '.environment_variables //empty')

    if [ ! -f "$manifest" ]; then
      echo "invalid payload (manifest is not a file: $manifest)"
      exit 1
    fi

    # add pipeline defined environment variables to the manifest
    for key in $(echo $environment_variables | jq -r 'keys[]');
    do
      value=$(echo $environment_variables | jq -r --arg key "$key" '.[$key]')
      yaml w -i $manifest "env.$key" "$value"
    done

    args="-f $manifest"
    [ -n "$path" ] && args="$args -p $path"

    echo -e 'Executing \e[33m'"$command"$'\e[0m: '"$current_app_name"
    cf_target "$org" "$space"
    cf_zero_downtime_push "$args" "$current_app_name"
  elif [ "start" = "$command" ]; then
    app_name=$(echo $options | jq -r '.app_name //empty')
    staging_timeout=$(echo $options | jq -r '.staging_timeout //"0"')
    startup_timeout=$(echo $options | jq -r '.startup_timeout //"0"')
    echo -e 'Executing \e[33m'"$command"$'\e[0m: '"$app_name"
    cf_target "$org" "$space"
    cf_start "$app_name" "$staging_timeout" "$startup_timeout"
  elif [ "delete" = "$command" ]; then
    app_name=$(echo $options | jq -r '.app_name //empty')
    delete_mapped_routes=$(echo $options | jq -r '.delete_mapped_routes //empty')
    echo -e 'Executing \e[33m'"$command"$'\e[0m: '"$app_name"
    cf_target "$org" "$space"
    cf_delete "$app_name" "$delete_mapped_routes"
  elif [ "bind-service" = "$command" ]; then
    app_name=$(echo $options | jq -r '.app_name //empty')
    service_instance=$(echo $options | jq -r '.service_instance //empty')
    configuration=$(echo $options | jq -r '.configuration // "{}" //empty')
    echo -e 'Executing \e[33m'"$command"$'\e[0m: '"$app_name"
    cf_target "$org" "$space"
    cf_bind_service "$app_name" "$service_instance" "$configuration"
  else
    echo "invalid payload (unknown command: $command)"
    exit 1
  fi
done

# todo: metadata
jq -n \
--arg timestamp $(date +%s) \
'{
  version: {
    timestamp: $timestamp
  }
}' >&3
