#!/bin/bash

set -eu
set -o pipefail

test_dir=$(dirname $0)

source $test_dir/config.sh
source $test_dir/helpers.sh

run cleanup_test_orgs
run cleanup_test_users
run cleanup_service_brokers
run cleanup_buildpacks
