#!/bin/bash

set -eu
set -o pipefail

test_dir=$(dirname $0)

source $test_dir/config.sh
source $test_dir/helpers.sh

# Add origin to auth config
source=$(echo $source | jq '.source.origin = "uaa"')

org=$(generate_test_name_with_spaces "Org")
space=$(generate_test_name_with_spaces "Space")

setup_integration_tests "$org" "$space"
teardown_integration_tests "$org" "$space"
