#!/bin/bash

set -eu
set -o pipefail

base_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)

source "$base_dir/itest/lib/assert.sh"
source "$base_dir/itest/lib/helpers.sh"
source "$base_dir/itest/lib/config.sh"

it_can_wait_for_service() {
  local org=${1:?org null or not set}
  local space=${2:?space null or not set}
  local service_instance=${3:?service_instance null or not set}

  local params=$(jq -n \
  --arg org "$org" \
  --arg space "$space" \
  --arg service_instance "$service_instance" \
  '{
    command: "wait-for-service",
    org: $org,
    space: $space,
    service_instance: $service_instance
  }')

  put_with_params "$CCR_SOURCE" "$params" | jq -e '.version | keys == ["timestamp"]'

  assert::success cf::service_exists "$service_instance"
}

org=$(generate_test_name_with_spaces "Org")
space=$(generate_test_name_with_spaces "Space")
app_name=$(generate_test_name_with_spaces "App")

service=$CCR_ASYNC_SERVICE
plan_1=$CCR_ASYNC_PLAN_1
plan_2=$CCR_ASYNC_PLAN_2
service_instance=$(generate_test_name_with_spaces "Async Service")
broker=$service
configuration_1=$CCR_ASYNC_CONFIGURATION_1
configuration_2=$CCR_ASYNC_CONFIGURATION_2
tags="list, of, tags"
wait_for_service="true"
update_service="true"

setup_integration_tests "$org" "$space"

describe "create a service that does not exist without specifying a broker and wait for it"
{
  empty_broker_value=""
  run it_can_create_a_service \"$org\" \"$space\" \"$service\" \"$plan_1\" \"$service_instance\" \"$empty_broker_value\" \"$configuration_1\"
  run it_can_wait_for_service \"$org\" \"$space\" \"$service_instance\"
}

describe "create a service that already exists"
{
  run it_can_create_a_service \"$org\" \"$space\" \"$service\" \"$plan_1\" \"$service_instance\" \"$broker\" \"$configuration_1\"
}

describe "create a service that already exists and update with changes"
{
  run it_can_create_a_service \"$org\" \"$space\" \"$service\" \"$plan_2\" \"$service_instance\" \"$broker\" \"$configuration_2\" \"$wait_for_service\" \"$update_service\"
}

describe "create a service that already exists and update without changes"
{
  run it_can_create_a_service \"$org\" \"$space\" \"$service\" \"$plan_2\" \"$service_instance\" \"$broker\" \"$configuration_2\" \"$wait_for_service\" \"$update_service\"
}

describe "update a service"
{
  run it_can_update_a_service \"$org\" \"$space\" \"$service_instance\" \"$plan_1\" \"$configuration_1\" \"$tags\" \"$wait_for_service\"
}

describe "bind, unbind, and delete a service"
{
  run it_can_push_an_app \"$org\" \"$space\" \"$app_name\"

  run it_can_bind_a_service \"$org\" \"$space\" \"$app_name\" \"$service_instance\"
  run it_can_unbind_a_service \"$org\" \"$space\" \"$app_name\" \"$service_instance\"
  run it_can_delete_a_service \"$org\" \"$space\" \"$service_instance\"

  run it_can_delete_an_app \"$org\" \"$space\" \"$app_name\"
}

teardown_integration_tests "$org" "$space"
