#!/bin/bash

set -eu
set -o pipefail

base_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)

source "$base_dir/itest/lib/helpers.sh"
source "$base_dir/itest/lib/config.sh"

it_can_push_an_app_with_client_credentials() {
  # switch from username/password to client_id/client_secret
  CCR_SOURCE=$(echo $CCR_SOURCE | jq \
  --arg client_id "$CCR_CF_CLIENT_ID" \
  --arg client_secret "$CCR_CF_CLIENT_SECRET" \
  '
    del(.source.username) | del(.source.password)
    |
    .source.client_id = $client_id | .source.client_secret = $client_secret
  ')

  it_can_push_an_app "$@"
}

org=$(generate_test_name_with_spaces "Org")
space=$(generate_test_name_with_spaces "Space")
app_name=$(generate_test_name_with_spaces "App")

setup_integration_tests "$org" "$space"

run it_can_push_an_app_with_client_credentials \"$org\" \"$space\" \"$app_name\"

teardown_integration_tests "$org" "$space"
