#!/bin/bash

set -eu
set -o pipefail

base_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)

source "$base_dir/itest/lib/helpers.sh"
source "$base_dir/itest/lib/config.sh"

# switch from username/password to client_id/client_secret
CCR_SOURCE=$(echo $CCR_SOURCE | jq \
--arg client_id "$CCR_CF_CLIENT_ID" \
--arg client_secret "$CCR_CF_CLIENT_SECRET" \
'
  del(.source.username) | del(.source.password)
  |
  .source.client_id = $client_id | .source.client_secret = $client_secret
')

org=$(generate_test_name_with_spaces "Org")
space=$(generate_test_name_with_spaces "Space")

setup_integration_tests "$org" "$space"
teardown_integration_tests "$org" "$space"
