#!/bin/bash

set -eu
set -o pipefail

base_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)

source "$base_dir/itest/lib/helpers.sh"
source "$base_dir/itest/lib/config.sh"

# Add origin to auth config
CCR_SOURCE=$(echo $CCR_SOURCE | jq '.source.origin = "uaa"')

org=$(generate_test_name_with_spaces "Org")
space=$(generate_test_name_with_spaces "Space")

setup_integration_tests "$org" "$space"
teardown_integration_tests "$org" "$space"
