#!/bin/bash

set -eu
set -o pipefail

test_dir=$(dirname $0)

source $test_dir/config.sh
source $test_dir/helpers.sh
source $test_dir/assert.sh

it_can_create_a_user_with_password() {
  local org=${1:?org null or not set}
  local space=${2:?space null or not set}
  local username=${3:?username null or not set}
  local password=${4:?password null or not set}

  local params=$(jq -n \
  --arg org "$org" \
  --arg space "$space" \
  --arg username "$username" \
  --arg password "$password" \
  '{
    command: "create-user",
    org: $org,
    space: $space,
    username: $username,
    password: $password
  }')

  put_with_params "$source" "$params" | jq -e '.version | keys == ["timestamp"]'

  assert::success cf_user_exists "$username"
}

it_can_create_a_user_with_origin() {
  local org=${1:?org null or not set}
  local space=${2:?space null or not set}
  local username=${3:?username null or not set}
  local origin=${4:?origin null or not set}

  local params=$(jq -n \
  --arg org "$org" \
  --arg space "$space" \
  --arg username "$username" \
  --arg origin "$origin" \
  '{
    command: "create-user",
    org: $org,
    space: $space,
    username: $username,
    origin: $origin
  }')

  put_with_params "$source" "$params" | jq -e '.version | keys == ["timestamp"]'

  assert::success cf_user_exists "$username" "$origin"
}

it_can_create_users_from_file() {
  local org=${1:?org null or not set}
  local space=${2:?space null or not set}

  local working_dir=$(mktemp -d $TMPDIR/put-src.XXXXXX)

  mkdir -p $working_dir/input

  cat << EOF > $working_dir/input/users.csv
Username,Password,Org,Space,OrgManager,BillingManager,OrgAuditor,SpaceManager,SpaceDeveloper,SpaceAuditor
$test_prefix-bulkload-user1,wasabi,$org,$space,x,x,x,x,x,x
$test_prefix-bulkload-user2,wasabi,$org,$space,,x,x,,x,x
$test_prefix-bulkload-user3,ldap,$org,$space,,,x,,x,
EOF

  local params=$(jq -n \
  --arg org "$org" \
  --arg space "$space" \
  '{
    command: "create-users-from-file",
    org: $org,
    space: $space,
    file: "input/users.csv"
  }')

  put_with_params "$source" "$params" "$working_dir" | jq -e '.version | keys == ["timestamp"]'

  assert::success cf_user_exists "$test_prefix-bulkload-user1"
  assert::success cf_user_exists "$test_prefix-bulkload-user2"
  assert::success cf_user_exists "$test_prefix-bulkload-user3"
}

it_can_delete_a_user_with_origin() {
  local org=${1:?org null or not set}
  local space=${2:?space null or not set}
  local username=${3:?username null or not set}

  local params=$(jq -n \
  --arg org "$org" \
  --arg space "$space" \
  --arg username "$username" \
  '{
    command: "delete-user",
    org: $org,
    space: $space,
    username: $username
  }')

  put_with_params "$source" "$params" | jq -e '.version | keys == ["timestamp"]'

  assert::failure cf_user_exists "$username"
}

it_can_delete_a_user_with_password() {
  local org=${1:?org null or not set}
  local space=${2:?space null or not set}
  local username=${3:?username null or not set}

  local params=$(jq -n \
  --arg org "$org" \
  --arg space "$space" \
  --arg username "$username" \
  '{
    command: "delete-user",
    org: $org,
    space: $space,
    username: $username
  }')

  put_with_params "$source" "$params" | jq -e '.version | keys == ["timestamp"]'

  assert::failure cf_user_exists "$username"
}

org=$(generate_test_name_with_spaces "Org")
space=$(generate_test_name_with_spaces "Space")
username=$(generate_test_name_with_hyphens "User")
password=$(generate_test_name_with_spaces "Password")
origin_username=$(generate_test_name_with_hyphens "Origin User")

setup_integration_tests "$org" "$space"

run it_can_create_a_user_with_password \"$org\" \"$space\" \"$username\" \"$password\"
run it_can_create_a_user_with_origin \"$org\" \"$space\" \"$origin_username\" "sso"
run it_can_create_users_from_file \"$org\" \"$space\"

run it_can_delete_a_user_with_origin \"$org\" \"$space\" \"$origin_username\"
run it_can_delete_a_user_with_password \"$org\" \"$space\" \"$username\"

teardown_integration_tests "$org" "$space"
