#!/bin/bash

set -eu
set -o pipefail

test_dir=$(dirname $0)

source $test_dir/helpers.sh
source $test_dir/config.sh

org=$(generate_test_name_with_spaces "Org")
space=$(generate_test_name_with_spaces "Space")

setup_integration_tests "$org" "$space"

run it_can_disable_feature_flag \"service_instance_sharing\"
run it_can_enable_feature_flag \"service_instance_sharing\"

teardown_integration_tests "$org" "$space"
