#!/bin/bash

set -eu
set -o pipefail

test_dir=$(dirname $0)

source $test_dir/assert.sh
source $test_dir/helpers.sh
source $test_dir/config.sh

it_can_push_an_app_no_start_with_file() {
  local working_dir=$(mktemp -d $TMPDIR/put-src.XXXXXX)

  create_static_app "$3" "$working_dir"

  mkdir "$working_dir/file-tests"
  cat > "$working_dir/file-tests/commands.yml" <<-EOF
command: push
org: $1
space: $2
app_name: $3
path: static-*/content
manifest: static-app/manifest.yml
no_start: true
EOF

  local params=$(jq -n \
  --arg command_file "file-tests/commands.yml" \
  '{
    command: "invalid-XXXXXX",
    command_file: $command_file
  }')

  local config=$(echo $source | jq --argjson params "$params" '.params = $params')

  put_with_params "$config" "$working_dir" | jq -e '
    .version | keys == ["timestamp"]
  '

  assert::success cf_is_app_stopped "$3"
}


it_can_start_an_app_with_file() {
  local working_dir=$(mktemp -d $TMPDIR/put-src.XXXXXX)

  mkdir "$working_dir/file-tests"
  cat > "$working_dir/file-tests/commands.yml" <<-EOF
command: start
org: $1
space: $2
app_name: $3
staging_timeout: 15
startup_timeout: 5
EOF

  local params=$(jq -n \
  --arg command_file "file-tests/commands.yml" \
  '{
    command: "invalid-XXXXXX",
    command_file: $command_file
  }')

  local config=$(echo $source | jq --argjson params "$params" '.params = $params')

  put_with_params "$config" "$working_dir" | jq -e '
    .version | keys == ["timestamp"]
  '

  assert::success cf_is_app_started "$3"
}

it_can_stop_an_app_with_file() {
  local working_dir=$(mktemp -d $TMPDIR/put-src.XXXXXX)

  mkdir "$working_dir/file-tests"
  cat > "$working_dir/file-tests/commands.yml" <<-EOF
command: stop
org: $1
space: $2
app_name: $3
EOF

  local params=$(jq -n \
  --arg command_file "file-tests/commands.yml" \
  '{
    command: "invalid-XXXXXX",
    command_file: $command_file
  }')

  local config=$(echo $source | jq --argjson params "$params" '.params = $params')

  put_with_params "$config" "$working_dir" | jq -e '
    .version | keys == ["timestamp"]
  '
  assert::success cf_is_app_stopped "$3"
}

it_can_delete_an_app_with_file() {
  local working_dir=$(mktemp -d $TMPDIR/put-src.XXXXXX)

  mkdir "$working_dir/file-tests"
  cat > "$working_dir/file-tests/commands.yml" <<-EOF
command: delete
org: $1
space: $2
app_name: $3
delete_mapped_routes: true
EOF

  local params=$(jq -n \
  --arg command_file "file-tests/commands.yml" \
  '{
    command: "invalid-XXXXXX",
    command_file: $command_file
  }')

  local config=$(echo $source | jq --argjson params "$params" '.params = $params')

  put_with_params "$config" "$working_dir" | jq -e '
    .version | keys == ["timestamp"]
  '

  assert::failure cf_app_exists "$3"
}

it_can_create_an_org_with_file() {
  local working_dir=$(mktemp -d $TMPDIR/put-src.XXXXXX)

  mkdir "$working_dir/file-tests"
  cat > "$working_dir/file-tests/commands.yml" <<-EOF
command: create-org
org: $1
EOF

  local params=$(jq -n \
  --arg command_file "file-tests/commands.yml" \
  '{
    command: "invalid-XXXXXX",
    command_file: $command_file
  }')

  local config=$(echo $source | jq --argjson params "$params" '.params = $params')

  put_with_params "$config" "$working_dir" | jq -e '
    .version | keys == ["timestamp"]
  '

  assert::success cf_org_exists "$1"
}

it_can_create_a_space_with_file() {
  local working_dir=$(mktemp -d $TMPDIR/put-src.XXXXXX)

  mkdir "$working_dir/file-tests"
  cat > "$working_dir/file-tests/commands.yml" <<-EOF
command: create-space
org: $1
space: $2
EOF

  local params=$(jq -n \
  --arg command_file "file-tests/commands.yml" \
  '{
    command: "invalid-XXXXXX",
    command_file: $command_file
  }')

  local config=$(echo $source | jq --argjson params "$params" '.params = $params')

  put_with_params "$config" "$working_dir" | jq -e '
    .version | keys == ["timestamp"]
  '

  assert::success cf_space_exists "$1" "$2"
}

# This test showcases the multi-command syntax
it_can_delete_a_space_and_org_with_file() {
  local working_dir=$(mktemp -d $TMPDIR/put-src.XXXXXX)

  mkdir "$working_dir/file-tests"
  cat > "$working_dir/file-tests/commands.yml" <<-EOF
commands:
- command: delete-space
  org: $1
  space: $2
- command: delete-org
  org: $1
EOF

  local params=$(jq -n \
  --arg command_file "file-tests/commands.yml" \
  '{
    command: "invalid-XXXXXX",
    command_file: $command_file
  }')

  local config=$(echo $source | jq --argjson params "$params" '.params = $params')

  put_with_params "$config" "$working_dir" | jq -e '
    .version | keys == ["timestamp"]
  '

  assert::failure cf_space_exists "$1" "$2"
  assert::failure cf_org_exists "$1"
}


setup_integration_tests_with_file() {
  local org=${1:?org null or not set}
  local space=${2:?space null or not set}

  run it_can_create_an_org_with_file \"$org\"
  run it_can_create_a_space_with_file \"$org\" \"$space\"
}

teardown_integration_tests_with_file() {
  local org=${1:?org null or not set}
  local space=${2:?space null or not set}

  run it_can_delete_a_space_and_org_with_file \"$org\" \"$space\"
}

org=$(generate_test_name_with_spaces "Org")
space=$(generate_test_name_with_spaces "Space")
app_name=$(generate_test_name_with_spaces "App")

setup_integration_tests_with_file "$org" "$space"

run it_can_push_an_app_no_start_with_file \"$org\" \"$space\" \"$app_name\"
run it_can_start_an_app_with_file \"$org\" \"$space\" \"$app_name\"
run it_can_stop_an_app_with_file \"$org\" \"$space\" \"$app_name\"
run it_can_delete_an_app_with_file \"$org\" \"$space\" \"$app_name\"

teardown_integration_tests_with_file "$org" "$space"
