#!/bin/bash

set -eu
set -o pipefail

test_dir=$(dirname $0)

source $test_dir/helpers.sh
source $test_dir/config.sh

it_can_add_network_policy() {
  local working_dir=$(mktemp -d $TMPDIR/put-src.XXXXXX)

  local params=$(jq -n \
  --arg org "$1" \
  --arg space "$2" \
  --arg source_app "$3" \
  --arg destination_app "$4" \
  '{
    command: "add-network-policy",
    org: $org,
    space: $space,
    source_app: $source_app,
    destination_app: $destination_app,
    protocol: "udp",
    port: "9999"
  }')

  local config=$(echo $source | jq --argjson params "$params" '.params = $params')

  put_with_params "$config" "$working_dir" | jq -e '
    .version | keys == ["timestamp"]
  '

  cf_network_policy_exists "$3" "$4" "udp" "9999"
}

it_can_remove_network_policy() {
  local working_dir=$(mktemp -d $TMPDIR/put-src.XXXXXX)

  local params=$(jq -n \
  --arg org "$1" \
  --arg space "$2" \
  --arg source_app "$3" \
  --arg destination_app "$4" \
  '{
    command: "remove-network-policy",
    org: $org,
    space: $space,
    source_app: $source_app,
    destination_app: $destination_app,
    protocol: "udp",
    port: "9999"
  }')

  local config=$(echo $source | jq --argjson params "$params" '.params = $params')

  put_with_params "$config" "$working_dir" | jq -e '
    .version | keys == ["timestamp"]
  '

  ! cf_network_policy_exists "$1" "$2" "udp" "9999"
}

org=$(generate_test_name_with_spaces "Org")
space=$(generate_test_name_with_spaces "Space")
source_app_name=$(generate_test_name_with_spaces "Source App")
destination_app_name=$(generate_test_name_with_spaces "Destination App")

setup_integration_tests "$org" "$space"

run it_can_push_an_app \"$org\" \"$space\" \"$source_app_name\"
run it_can_push_an_app \"$org\" \"$space\" \"$destination_app_name\"

run it_can_add_network_policy \"$org\" \"$space\" \"$source_app_name\" \"$destination_app_name\"
run it_can_remove_network_policy \"$org\" \"$space\" \"$source_app_name\" \"$destination_app_name\"

run it_can_delete_an_app \"$org\" \"$space\" \"$destination_app_name\"
run it_can_delete_an_app \"$org\" \"$space\" \"$source_app_name\"

teardown_integration_tests "$org" "$space"
