#!/bin/bash

set -eu
set -o pipefail

base_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)

"$base_dir/itest/cleanup-failed-tests"

"$base_dir/itest/run-validation-tests"
"$base_dir/itest/run-auth-cf-home-tests"

"$base_dir/itest/run-app-push-tests"
"$base_dir/itest/run-app-tests"
"$base_dir/itest/run-app-zero-downtime-push-tests"
"$base_dir/itest/run-asynchronous-service-tests"
"$base_dir/itest/run-auth-client-credentials-tests"
"$base_dir/itest/run-auth-origin-tests"
"$base_dir/itest/run-buildpack-tests"
"$base_dir/itest/run-docker-tests"
"$base_dir/itest/run-file-tests"
"$base_dir/itest/run-manifest-manipulation-tests"
"$base_dir/itest/run-network-policy-tests"
"$base_dir/itest/run-route-service-tests"
"$base_dir/itest/run-route-tests"
"$base_dir/itest/run-service-broker-tests"
"$base_dir/itest/run-service-key-tests"
"$base_dir/itest/run-share-service-tests"
"$base_dir/itest/run-synchronous-service-tests"
"$base_dir/itest/run-task-tests"
"$base_dir/itest/run-user-provided-service-tests"
"$base_dir/itest/run-user-tests"
