#!/bin/bash

set -eu
set -o pipefail

test_dir=$(dirname $0)

source $test_dir/config.sh
source $test_dir/helpers.sh

it_can_push_an_app() {
  local org=${1:?org null or not set}
  local space=${2:?space null or not set}
  local app_name=${3:?app_name null or not set}

  local project=$(create_bookstore_service_broker_app)

  local params=$(jq -n \
  --arg org "$org" \
  --arg space "$space" \
  --arg app_name "$app_name" \
  --arg path "$project/build/libs/bookstore-service-broker-*.jar" \
  --arg manifest "$project/deploy/cloudfoundry/manifest.yml" \
  '{
    command: "push",
    org: $org,
    space: $space,
    app_name: $app_name,
    path: $path,
    manifest: $manifest
  }')

  put_with_params "$CCR_SOURCE" "$params" | jq -e '.version | keys == ["timestamp"]'

  assert::success cf::is_app_started "$app_name"
}

it_can_create_a_service_broker() {
  local service_broker=${1:?service_broker null or not set}
  local url=${2:?url null or not set}

  local params=$(jq -n \
    --arg service_broker "$service_broker" \
    --arg username admin \
    --arg password supersecret \
    --arg url "$url" \
    '{
      command: "create-service-broker",
      service_broker: $service_broker,
      username: $username,
      password: $password,
      url: $url
    }')

  put_with_params "$CCR_SOURCE" "$params" | jq -e '.version | keys == ["timestamp"]'

  assert::success cf::service_broker_exists "$service_broker"
}

it_can_enable_service_access() {
  local org=${1:?org null or not set}
  local space=${2:?space null or not set}
  local service_broker=${3:?service_broker null or not set}

  local params=$(jq -n \
    --arg service_broker "$service_broker" \
    '{
      command: "enable-service-access",
      service_broker: $service_broker
    }')

  put_with_params "$CCR_SOURCE" "$params" | jq -e '.version | keys == ["timestamp"]'

  cf::target "$org" "$space"
  assert::success cf::is_marketplace_service_available "$service_broker"
}

org=service-brokers
space=bookstore

setup_integration_tests "$org" "$space"
run it_can_push_an_app \"$org\" \"$space\" \"bookstore-service-broker\"
run it_can_create_a_service_broker \"bookstore\" \"https://bookstore-service-broker.$CCR_CF_APPS_DOMAIN\"
run it_can_enable_service_access \"$org\" \"$space\" \"bookstore\"

run it_can_push_an_app \"$org\" \"$space\" \"bookstore-service-broker-async\"
run it_can_create_a_service_broker \"bookstore-async\" \"https://bookstore-service-broker-async.$CCR_CF_APPS_DOMAIN\"
run it_can_enable_service_access \"$org\" \"$space\" \"bookstore-async\"
